### ISSUE TITLE
list.files("/opt/R") returning character(0) on 1.x

### ISSUE THREAD

**Issue by hughjonesd** [r-hub/evercran#7]
On a fresh container of 1.x, running `/opt/R/1.0.0/bin/R` (or other versions):

```r
> list.files("/opt/R")
character(0)
> list.files("/usr/lib/perl")
character(0)
```

Is this a permissions issue? I'm logged in as root and bash `ls` returns the expected result. Other directories also return a normal result:

```r
> list.files("/usr/lib/mime/packages/")
[1] "debianutils" "groff-base"  "less"        "tar"         "util-linux" 
```

**Comment by gaborcsardi** [comment]
I think that's a bug in Docker, when you run an i386 container on aarch64 processor, unfortunately.

**Comment by hughjonesd** [comment]
Do you by chance know if there's an issue for this on Docker?

**Comment by gaborcsardi** [comment]
I don't remember. Not many people use the `i386` arch on Docker or qemu. 

If you have a script to run, it is best to run it on GH actions, which is intel, or I can also run it.

**Comment by gaborcsardi** [comment]
I have some memories that it has to do with the file system (?) using large integers, which is not handled by the OS. Something like this.

**Comment by gaborcsardi** [comment]
I found this: https://github.com/docker/buildx/issues/395

> Somewhere I read that this is an Issue with qemu emulating an 32bit system on an 64bit host.

This is a good way to reproduce, because R ignores the system errors in `list.files()` (!):

```
56d7cfb548b9:~# find /opt/R
/opt/R
find: /opt/R: Value too large for defined data type
```

**Comment by gaborcsardi** [comment]
I possibly found a silly workaround. If you bind mount a volume, and copy the whole of `/opt/R` over there, then remove `/opt/R` and then symlink it to the mounted volume, then things seems to work better.

**Comment by gaborcsardi** [comment]
Still an issue with Docker 24.0.6 on macOS. I don't think this is going to be fixed. 

But I found a workaround based on https://www.mjr19.org.uk/sw/inodes64.html It works pretty well, I am going to add it to the Docker images, or possibly to the DEB packages even:
```
77d2f1f438e2:~# echo 'list.files("/opt/R")' | /opt/R/1.0.0/bin/R  -q --vanilla
> list.files("/opt/R")
character(0)
> 
77d2f1f438e2:~# echo 'list.files("/opt/R")' | fix32 /opt/R/1.0.0/bin/R  -q --vanilla
> list.files("/opt/R")
 [1] "1.0.0" "1.0.1" "1.1.0" "1.1.1" "1.2.0" "1.2.1" "1.2.2" "1.2.3" "1.3.0"
[10] "1.3.1" "1.4.0" "1.4.1" "1.5.0" "1.5.1" "1.6.0" "1.6.1" "1.6.2" "1.7.0"
[19] "1.7.1" "1.8.0" "1.8.1" "1.9.0" "1.9.1"
```

**Comment by gaborcsardi** [comment]
This should be fixed now and work OOTB.

**Comment by hughjonesd** [comment]
Is it merged for the 1.x image? I still get the issue as of 18:30 UK time.

**Comment by hughjonesd** [comment]
I'm still getting the list.files() problem on 1.x. Should I be using a special command to run R?

**Comment by gaborcsardi** [comment]
This is macOS arm64:
```
❯ docker run --pull always -it ghcr.io/r-hub/evercran/1.x bash
latest: Pulling from r-hub/evercran/1.x
Digest: sha256:6c71408ee75154439519f9f7e69ec31ea9bfe5b9e18b95e92f786ee9ff392866
Status: Image is up to date for ghcr.io/r-hub/evercran/1.x:latest
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
```
b0e5c274aa4f:~# /opt/R/1.9.1/bin/R -q
> list.files("/opt/R")
 [1] "1.0.0" "1.0.1" "1.1.0" "1.1.1" "1.2.0" "1.2.1" "1.2.2" "1.2.3" "1.3.0"
[10] "1.3.1" "1.4.0" "1.4.1" "1.5.0" "1.5.1" "1.6.0" "1.6.1" "1.6.2" "1.7.0"
[19] "1.7.1" "1.8.0" "1.8.1" "1.9.0" "1.9.1"
> list.files("/usr/lib/perl")
[1] "5.8"   "5.8.4"
```

**Comment by gaborcsardi** [comment]
Can you share some details about your platform? OS vesion (`sw_vers`), `docker version`?

**Comment by hughjonesd** [comment]
This is indeed working for me, so it must be something about my build process. Sorry.

**Comment by hughjonesd** [comment]
Hmph.

```
~/rcheology$ docker create --pull always --name ctr-1.x -i -t "ghcr.io/r-hub/evercran/1.x"
latest: Pulling from r-hub/evercran/1.x
Digest: sha256:6c71408ee75154439519f9f7e69ec31ea9bfe5b9e18b95e92f786ee9ff392866
Status: Image is up to date for ghcr.io/r-hub/evercran/1.x:latest
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
f479275ee6e1fd0fdd21cd7120498a8269580b2fafe0561d1ddddc8519639307
~/rcheology$ docker start ctr-1.x
ctr-1.x
~/rcheology$ docker exec -i -t ctr-1.x bash
f479275ee6e1:~# /opt/R/1.9.1/bin/R -q
> list.files("/opt/R")
character(0)
> 
```

```
~/rcheology$ docker run --pull always -it ghcr.io/r-hub/evercran/1.x bash
latest: Pulling from r-hub/evercran/1.x
Digest: sha256:6c71408ee75154439519f9f7e69ec31ea9bfe5b9e18b95e92f786ee9ff392866
Status: Image is up to date for ghcr.io/r-hub/evercran/1.x:latest
WARNING: The requested image's platform (linux/386) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
38fee10d7757:~# /opt/R/1.9.1/bin/R -q                                       
> list.files("/opt/R")
 [1] "1.0.0" "1.0.1" "1.1.0" "1.1.1" "1.2.0" "1.2.1" "1.2.2" "1.2.3" "1.3.0"
[10] "1.3.1" "1.4.0" "1.4.1" "1.5.0" "1.5.1" "1.6.0" "1.6.1" "1.6.2" "1.7.0"
[19] "1.7.1" "1.8.0" "1.8.1" "1.9.0" "1.9.1"
```

**Comment by gaborcsardi** [comment]
When you do `docker exec` you are not running the entry point. You need to do
```
docker exec -i -t ctr-1.x entrypoint.sh bash
```

I guess we could set `LD_PRELOAD` at the system level to fix this, but on x86_64 we need to run programs with `linux32`, IDK how we could do that.

**Comment by gaborcsardi** [comment]
@hughjonesd I added a FAQ section to the README: https://github.com/r-hub/evercran#frequently-asked-questions

**Comment by hughjonesd** [comment]
This indeed works for me. Thanks for your help!
